ptrs: pointersxpointers.cpp char_pointers.cpp
	clang++ pointersxpointers.cpp -o pointersxpointers
	clang++ char_pointers.cpp -o char_pointers
	./pointersxpointers
	./char_pointers

.PHONY: clean
clean:
	rm -f make
